import type { PgTable } from "drizzle-orm/pg-core";

export type ColumnType = "string" | "number" | "date" | "boolean" | "integer";

export interface ColumnDef {
  /** Unique key used in data objects — must be unique across parent + child columns */
  field: string;
  /** Actual database column name. Defaults to `field` when omitted.
   *  Use when `field` is renamed to avoid parent/child name collisions. */
  dbField?: string;
  header: string;
  type: ColumnType;
  required?: boolean;
  sample?: string;
  exportOnly?: boolean;
}

export interface ForeignKeyLookup {
  /** The FK field on this entity (e.g. "accountTypeId") */
  field: string;
  /** The Drizzle table to look up against */
  lookupTable: PgTable;
  /** The column on the lookup table to match the CSV value (e.g. "name") */
  lookupField: string;
  /** The column on the lookup table used in CSV headers (human-readable) */
  displayField: string;
  /** Optional: scope lookups to the current org */
  orgScoped?: boolean;
}

export interface ProtectedFieldCheck {
  field: string;
  value: unknown;
  reason: string;
}

export interface ChildConfig {
  childTable: PgTable;
  childColumns: ColumnDef[];
  parentFkField: string;
  childForeignKeyLookups?: ForeignKeyLookup[];
}

export interface EntityConfig {
  slug: string;
  label: string;
  table: PgTable;
  columns: ColumnDef[];
  idField: string;
  orgScoped: boolean;
  protectedFieldChecks?: ProtectedFieldCheck[];
  computedFields?: string[];
  foreignKeyLookups?: ForeignKeyLookup[];
  selfReferentialField?: string;
  childConfig?: ChildConfig;
  autoGeneratedFields?: string[];
}

export type RowStatus = "create" | "update" | "error" | "skipped";

export interface PreviewRow {
  index: number;
  status: RowStatus;
  data: Record<string, unknown>;
  resolvedData?: Record<string, unknown>;
  /** Original CSV row keyed by CSV header names (for display in preview table) */
  rawRow?: Record<string, string>;
  errors: string[];
  warnings: string[];
}

export interface PreviewResult {
  summary: {
    total: number;
    creates: number;
    updates: number;
    errors: number;
    skipped: number;
  };
  rows: PreviewRow[];
  headers: string[];
}

export interface ImportResult {
  imported: number;
  updated: number;
  skipped: number;
  failed: number;
  errors: { row: number; field?: string; message: string }[];
}

export const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const MAX_ROW_COUNT = 10_000;
export const CSV_BOM = "\uFEFF";
