import {
  journalEntries,
  journalLines,
  accountingPeriods,
  chartOfAccounts,
} from "@/lib/db/schema";
import type { EntityConfig } from "../types";

export const journalEntriesConfig: EntityConfig = {
  slug: "journal-entries",
  label: "Journal Entries",
  table: journalEntries,
  idField: "id",
  orgScoped: true,
  computedFields: ["totalDebit", "totalCredit", "baseCurrencyDebit", "baseCurrencyCredit"],
  autoGeneratedFields: ["entryNumber"],
  protectedFieldChecks: [
    { field: "isDemo", value: true, reason: "Demo record skipped" },
  ],
  foreignKeyLookups: [
    {
      field: "periodId",
      lookupTable: accountingPeriods,
      lookupField: "name",
      displayField: "name",
      orgScoped: true,
    },
  ],
  columns: [
    { field: "id", header: "ID", type: "string" },
    { field: "entryNumber", header: "Entry Number", type: "string", required: true, sample: "JE-202503-0001" },
    { field: "entryDate", header: "Entry Date", type: "date", required: true, sample: "2025-03-15" },
    { field: "description", header: "Description", type: "string", required: true, sample: "Monthly rent payment" },
    { field: "reference", header: "Reference", type: "string", sample: "INV-001" },
    { field: "sourceType", header: "Source Type", type: "string", sample: "manual" },
    { field: "status", header: "Status", type: "string", sample: "posted" },
    { field: "periodId", header: "Period", type: "string", required: true, sample: "March 2025" },
    { field: "currency", header: "Currency", type: "string", sample: "AED" },
    { field: "exchangeRate", header: "Exchange Rate", type: "number", sample: "1" },
    { field: "totalDebit", header: "Total Debit", type: "number", exportOnly: true },
    { field: "totalCredit", header: "Total Credit", type: "number", exportOnly: true },
  ],
  childConfig: {
    childTable: journalLines,
    parentFkField: "journalEntryId",
    childForeignKeyLookups: [
      {
        field: "accountId",
        lookupTable: chartOfAccounts,
        lookupField: "code",
        displayField: "code",
        orgScoped: true,
      },
    ],
    childColumns: [
      { field: "accountId", header: "Line Account Code", type: "string", required: true, sample: "6100" },
      { field: "lineDescription", dbField: "description", header: "Line Description", type: "string", sample: "Rent expense" },
      { field: "debit", header: "Debit", type: "number", sample: "5000.00" },
      { field: "credit", header: "Credit", type: "number", sample: "0.00" },
      { field: "lineCurrency", dbField: "currency", header: "Line Currency", type: "string", sample: "AED" },
      { field: "lineExchangeRate", dbField: "exchangeRate", header: "Line Exchange Rate", type: "number", sample: "1" },
      { field: "baseCurrencyDebit", header: "Base Currency Debit", type: "number", exportOnly: true },
      { field: "baseCurrencyCredit", header: "Base Currency Credit", type: "number", exportOnly: true },
      { field: "taxCode", header: "Line Tax Code", type: "string" },
      { field: "taxAmount", header: "Line Tax Amount", type: "number" },
    ],
  },
};
